### ISSUE TITLE
Add Android bindings

### ISSUE THREAD

**Issue by andymatuschak** [andymatuschak/react-native-leveldown#1]
Right now, this project only has iOS/Mac bindings. I'd like to add Android bindings, too, but I don't have much experience with the Android build system, so I suspect it'll take me a while.

I'd be grateful for help! Looks like [there are already LevelDB JNI bindings we can use](https://github.com/litl/android-leveldb).

**Comment by RAN3000** [comment]
Hey, quick update: after a little trial and error, I managed to set up the project on my machine and run the Android version of `testapp`. I will now proceed with the implementation of the bindings.

**Comment by andymatuschak** [comment]
Rad! Thanks so much for giving it a try, @RAN3000!

**Comment by RAN3000** [comment]
I finally got all tests to pass! 

I have to clean up the code, then I'll create a pull request.

**Comment by andymatuschak** [comment]
Fantastic—how exciting! High-performance object stores for cross-platform clients: that's a great thing.
